"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os
from django.core.exceptions import ImproperlyConfigured


env = environ.Env(
    # Set default values and casting
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-^x8@@0@p@j$0a1_8p-9bb^g7)z9me2t$)a4a2yajb$^^a0sudz')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'accounts',
    'packages',
    'payments',
    'content',
]

# --- REST Framework & JWT ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# --- Media files (portfolio images, editing uploads) ---
# On Railway: attach a Volume to K_app mounted at /app/media (or set MEDIA_ROOT),
# otherwise uploads disappear on every deploy. Prefer S3/R2 for production photos.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(env('MEDIA_ROOT', default=str(BASE_DIR / 'media')))
# True when using local disk (volume or ephemeral). False when using S3/R2.
USE_LOCAL_MEDIA = True

# --- Consistent primary key type ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]
try:
    import whitenoise  # noqa: F401
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass
MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Postgres: set DATABASE_URL (local Docker, Railway, etc.). For hosted Postgres that
# requires SSL, add ?sslmode=require to the URL.
# If DATABASE_URL is unset, SQLite is used (simple clone / CI without Docker).
_default_sqlite = 'sqlite:///' + (BASE_DIR / 'db.sqlite3').as_posix()
DATABASES = {
    'default': env.db('DATABASE_URL', default=_default_sqlite),
}
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['timeout'] = env.int('SQLITE_TIMEOUT', default=20)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')
BOOKING_DEFAULT_PRICE = env('BOOKING_DEFAULT_PRICE', default='150.00')

STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')
GETADDRESS_API_KEY = env('GETADDRESS_API_KEY', default='')

EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=20)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='hello@kaytubillla.com')
# Prefer Resend on Railway if Gmail SMTP hangs (outbound SMTP often blocked).
RESEND_API_KEY = env('RESEND_API_KEY', default='')
EMAIL_VERIFICATION_MINUTES = env.int('EMAIL_VERIFICATION_MINUTES', default=15)

# Google Sign-In (ID token audience). Client secret not required for GIS button flow.
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')

CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=['http://localhost:5173', 'http://localhost:3000'],
)
CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=['http://localhost:5173'],
)

CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optional S3 / R2 object storage (recommended for portfolio photos on Railway)
if env('AWS_STORAGE_BUCKET_NAME', default=''):
    import re

    INSTALLED_APPS += ['storages']
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME').strip()
    # Must be a region id like eu-west-2 — NOT an AZ (eu-west-2a) or typo (eu-west-2-an).
    _raw_region = env('AWS_S3_REGION_NAME', default='eu-west-2').strip()
    _region_match = re.match(r'^([a-z]{2}-[a-z]+-\d+)', _raw_region)
    AWS_S3_REGION_NAME = _region_match.group(1) if _region_match else _raw_region
    if AWS_S3_REGION_NAME != _raw_region:
        import logging
        logging.getLogger(__name__).warning(
            'AWS_S3_REGION_NAME=%r normalized to %r (use the region id, e.g. eu-west-2)',
            _raw_region,
            AWS_S3_REGION_NAME,
        )
    if AWS_STORAGE_BUCKET_NAME.startswith('arn:') or '/' in AWS_STORAGE_BUCKET_NAME:
        raise ImproperlyConfigured(
            'AWS_STORAGE_BUCKET_NAME must be the short bucket name only '
            '(e.g. photolux-oxford-media), not an ARN or URL.'
        )
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
    # Many new buckets block ACLs — leave unset/public via bucket policy instead.
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_ADDRESSING_STYLE = 'virtual'
    # Only set these when non-empty. An empty AWS_S3_ENDPOINT_URL makes boto3 raise
    # ValueError: Invalid endpoint:  (breaks portfolio uploads on normal AWS S3).
    _s3_custom_domain = env('AWS_S3_CUSTOM_DOMAIN', default='').strip()
    _s3_endpoint_url = env('AWS_S3_ENDPOINT_URL', default='').strip()
    if _s3_custom_domain:
        AWS_S3_CUSTOM_DOMAIN = _s3_custom_domain
    if _s3_endpoint_url:
        AWS_S3_ENDPOINT_URL = _s3_endpoint_url
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }
    if _s3_custom_domain:
        MEDIA_URL = f'https://{_s3_custom_domain}/'
    elif _s3_endpoint_url:
        MEDIA_URL = f'{_s3_endpoint_url.rstrip("/")}/{AWS_STORAGE_BUCKET_NAME}/'
    else:
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
    USE_LOCAL_MEDIA = False

# --- Django Channels ---
ASGI_APPLICATION = 'backend.asgi.application'

# Redis is required for multi-process / production. Locally, if REDIS_URL is unset,
# use the in-memory layer so chat works with plain `runserver` (no Redis needed).
_REDIS_URL = env('REDIS_URL', default='').strip()
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
