# Generated by Django 6.0.1 on 2026-04-03 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_servicearea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['date', 'block']},
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='block',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('potential', 'Potential'), ('unavailable', 'Unavailable')], default='available', max_length=15),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('date', 'block')},
        ),
    ]
