# Generated by Django 6.0.1 on 2026-04-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_availabilityslot_block_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='block',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_time',
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_time',
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('potential', 'Potential'), ('unavailable', 'Unavailable')], max_length=15),
        ),
    ]
