# Generated by Django 6.0.1 on 2026-07-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_booking_quoted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
