# Generated by Django 6.0.1 on 2026-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_widen_payment_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslot',
            name='fit_mode',
            field=models.CharField(choices=[('cover', 'Cover (fill & crop)'), ('contain', 'Contain (show full image)')], default='cover', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslot',
            name='position_x',
            field=models.SmallIntegerField(default=50, help_text='Horizontal focal point 0-100 (left to right)'),
        ),
        migrations.AddField(
            model_name='heroslot',
            name='position_y',
            field=models.SmallIntegerField(default=50, help_text='Vertical focal point 0-100 (top to bottom)'),
        ),
    ]
