# Generated by Django 6.0.1 on 2026-08-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_hero_slot_positioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='editingrequest',
            name='package',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('plus', 'Plus'), ('bundle', 'Bundle')], default='', max_length=20),
        ),
    ]
