# Generated by Django 6.0.1 on 2026-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_editingrequest_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_schedule',
            field=models.TextField(blank=True, default='', help_text='Customer preferred date/time notes (schedule agreed via messages).'),
        ),
    ]
