# Generated by Django 6.0.1 on 2026-08-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_booking_preferred_schedule_and_admin_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='studio_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='studio_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='studio_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='studio_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
